### ISSUE TITLE
Following type is missing from type_to_name_dict IMM2-BACKUP

### ISSUE THREAD

**Issue by RalfAlbers** [lenovo/ansible-role-lxca-config#10]
Hi,

with the new version of pylxca_module.py is still an firmware-update not possible. The Error ist "Following type is missing from type_to_name_dict IMM2-BACKUP".

Modify the lines 970 in pylxca_module.py to 
    type_to_name_dict = {"XCC-BACKUP": ["XCC (Backup)"],
                         "IMM-BACKUP": ["IMM (Backup)"],
                         "IMM2-BACKUP": ["IMM2 (Backup)"],
                         "UEFI-BACKUP": ["UEFI (Backup)"]}

gives the error
"Following type is missing from type_to_name_dict"

**Comment by prabhosa** [comment]
Fix pushed, Please verify

**Comment by RalfAlbers** [comment]
The changes in https://github.com/lenovo/ansible-role-lxca-config/commit/efcf9e14380842cfeb200ba73af873d007cdb290 had I already done before in my environment.
The error with the fix changed to:
"Following type is missing from type_to_name_dict"

**Comment by prabhosa** [comment]
Kindly close the bug if issue is resolved

**Comment by RalfAlbers** [comment]
Issue "Following type is missing from type_to_name_dict IMM2-BACKUP" is replace by "Following type is missing from type_to_name_dict"
I'll open a new bug
