### ISSUE TITLE
"Following type is missing from type_to_name_dict"

### ISSUE THREAD

**Issue by RalfAlbers** [lenovo/ansible-role-lxca-config#12]
- name: "Update Firmware with baseline"
          pylxca_module:
            login_user: "{{ lxca_user }}"
            login_password: "{{ lxca_password }}"
            auth_url: "{{ lxca_url }}"
            command_options: update_firmware_all
            lxca_action: "apply"
            mode: "delayed"
            uuid_list: "A704502C6BDE11EA8BFF3A68DD28FFA7"

ended with message:
"Following type is missing from type_to_name_dict"

This is the view from xClarity:
![image](https://user-images.githubusercontent.com/44479345/125287146-dcec5f80-e31c-11eb-8bf4-f683792753b4.png)

**Comment by prabhosa** [comment]
will recreate the env and issue and update the bug

**Comment by RalfAlbers** [comment]
fixed with https://github.com/lenovo/ansible-role-lxca-config/pull/13
